modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/starforcraft/Interdimensional-Wireless-Transmitter/issues"
license = "MIT"
[[mods]]
modId = "interdimensionalwirelesstransmitter"
version = "${version}"
displayName = "Interdimensional Wireless Transmitter"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/interdimensional-wireless-transmitter"
logoFile="logo.png"
authors = "Ultramega"
description = "Interdimensional Wireless Transmitter is an addon for Refined Storage which adds a cross-dimensional transmitter with infinite range."

[[dependencies.interdimensionalwirelesstransmitter]]
modId = "refinedstorage"
type = "required"
versionRange = "2.0.0-milestone.4.14"
side = "BOTH"
